{% set name = "solar-data-tools" %}
{% set version = "1.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solar_data_tools-{{ version }}.tar.gz
  sha256: e4227a4ce1119b60050ef5c4278d2ebd1b506c37f841a0e846cf8a62e309f8b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools-scm
  run:
    - pip
    - python >=3.9
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - jupyter
    - matplotlib-base
    - seaborn
    - requests
    - pvlib
    - cvxpy
    - pykml
    - haversine
    - smart_open
    - sig-decomp
    - clarabel
    - qss
    - tqdm
    - spcqe
    - dask
    - distributed
    - dask-cloudprovider
    - graphviz
    - bokeh

test:
  imports:
    - solardatatools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/slacgismo/solar-data-tools
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Tools for performing common tasks on solar PV data signals
  doc_url: https://solar-data-tools.readthedocs.io/

extra:
  recipe-maintainers:
    - bmeyers
    - pluflou
    - MitchellAV
